saleor/dashboard/category/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.category_list, name='category-list'),
    url(r'^(?P<root_pk>[0-9]+)/$',
        views.category_list, name='category-list'),
    url(r'^add/$',
        views.category_create, name='category-add'),
    url(r'^(?P<root_pk>[0-9]+)/add/$',
        views.category_create, name='category-add'),
    url(r'^(?P<root_pk>[0-9]+)/edit/$',
        views.category_edit, name='category-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.category_delete, name='category-delete')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from text_unidecode import unidecode

from ...product.models import Category


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super(CategoryForm, self).__init__(*args, **kwargs)
        if self.instance.parent and self.instance.parent.hidden:
            self.fields['hidden'].widget.attrs['disabled'] = True

    class Meta:
        model = Category
        exclude = ['slug']

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))
        if self.parent_pk:
            self.instance.parent = get_object_or_404(
                Category, pk=self.parent_pk)
        if self.instance.parent and self.instance.parent.hidden:
            self.instance.hidden = True
        super(CategoryForm, self).save(commit=commit)
        self.instance.set_hidden_descendants(self.cleaned_data['hidden'])
        return self.instance

saleor/dashboard/category/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ...settings import DASHBOARD_PAGINATE_BY
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    categories = get_paginator_items(
        categories, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal/edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-list', kwargs={'root_pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

templates/dashboard/category/modal/confirm_delete.html
{% extends "dashboard/base_modal_confirm_delete.html" %}

{% load i18n %}
{% load mptt_tags %}

{% block action_url %}
{% url "dashboard:category-delete" pk=category.pk %}
{% endblock %}

{% block title %}
{% blocktrans with category=category trimmed context "Delete category modal title" %}
Delete category {{ category }}
{% endblocktrans %}
{% endblock %}

{% block content %}
{% blocktrans with category=category trimmed context "Delete category modal title" %}
Are you sure you want to delete category <strong>{{ category }}</strong>?
{% endblocktrans %}
{% if descendants %}
<p>
{% trans "The following child categories will be deleted:" context "Delete category form text about descendant categories" %}
<ul>
  {% recursetree descendants %}
  <li>
    {{ node.name }}
    {% if not node.is_leaf_node %}
      <ul class="children">
        {{ children }}
      </ul>
    {% endif %}
  </li>
  {% endrecursetree %}
</ul>
</p>
{% endif %}
{% if products_count %}
<p>
{% blocktrans count counter=products_count trimmed context "Delete category form text about products" %}
  There is one product in this category that will be deleted.
  {% plural %}
  There are {{ counter }} products in this category that will be deleted.
{% endblocktrans %}
</p>
{% endif %}
{% endblock content %}

templates/dashboard/category/modal/edit.html
{% load materializecss %}
{% load i18n %}
{% load mptt_tags %}

<form method="post" id="form-category" class="form-async" action="{% url "dashboard:category-edit" root_pk=category.pk %}" novalidate>
  {% csrf_token %}
  <div class="modal-content">
    <div class="row">
      <div class="col s12">
        <h5>
          {% blocktrans trimmed context "Edit category modal title" %}
            Edit {{ category }}
          {% endblocktrans %}
        </h5>
      </div>
    </div>
    <div class="row">
      {{ form.name|materializecss:"s8 m10" }}
      {{ form.hidden|materializecss:"s4 m2" }}
      {{ form.description|materializecss }}
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="modal-action btn-flat">
      {% trans "Update" context "Dashboard update action" %}
    </button>
    <a href="#!" class="modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>