saleor/dashboard/customer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.customer_list, name='customers'),
    url(r'^(?P<pk>[0-9]+)/$', views.customer_details, name='customer-details'),
    url(r'^(?P<pk>[0-9]+)/promote/$', views.customer_promote_to_staff,
        name='customer-promote')
]

saleor/dashboard/group/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.group_list, name='group-list'),
    url(r'^group-create/$', views.group_create, name='group-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.group_details, name='group-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.group_delete, name='group-delete')
]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group'),

    url(r'^(?P<group_pk>\d+)/invoice/$',
        views.order_invoice, name='order-invoice'),
    url(r'^(?P<group_pk>\d+)/packing-slips/$',
        views.order_packing_slip, name='order-packing-slips')]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .staff.urls import urlpatterns as staff_urls
from .group.urls import urlpatterns as groups_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .search.urls import urlpatterns as search_urls
from .sites.urls import urlpatterns as site_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^groups/', include(groups_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^search/', include(search_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/group/forms.py
from django import forms
from django.contrib.auth.models import Group

from ...core.permissions import get_permissions


class GroupPermissionsForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'permissions']

    permissions = forms.ModelMultipleChoiceField(
        queryset=get_permissions(),
        widget=forms.CheckboxSelectMultiple
    )

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/dashboard/category/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ...settings import DASHBOARD_PAGINATE_BY
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    categories = get_paginator_items(
        categories, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal/edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-list', kwargs={'root_pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Count, Max
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...userprofile.models import User
from ...settings import DASHBOARD_PAGINATE_BY
from ..views import staff_member_required, superuser_required


@staff_member_required
@permission_required('userprofile.view_user')
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True))
        .order_by('email'))
    customers = get_paginator_items(
        customers, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {'customers': customers}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
@permission_required('userprofile.view_user')
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related(
        'default_billing_address', 'default_shipping_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)


@superuser_required
def customer_promote_to_staff(request, pk):
    customer = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        customer.is_staff = True
        customer.save()
        msg = pgettext_lazy(
            'Dashboard message',
            'Customer %s promoted to staff member') % customer
        messages.success(request, msg)
        return redirect('dashboard:customer-details', pk=customer.pk)
    return TemplateResponse(
        request, 'dashboard/customer/modal/confirm_promote.html',
        {'customer': customer})

saleor/dashboard/discount/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...discount.models import Sale, Voucher
from ...settings import DASHBOARD_PAGINATE_BY
from ..views import staff_member_required
from . import forms


@staff_member_required
@permission_required('discount.view_sale')
def sale_list(request):
    sales = Sale.objects.prefetch_related('products').order_by('name')
    sales = get_paginator_items(
        sales, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {'sales': sales}
    return TemplateResponse(request, 'dashboard/discount/sale/list.html', ctx)


@staff_member_required
@permission_required('discount.edit_sale')
def sale_edit(request, pk=None):
    if pk:
        instance = get_object_or_404(Sale, pk=pk)
    else:
        instance = Sale()
    form = forms.SaleForm(
        request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save()
        msg = pgettext_lazy(
            'Sale (discount) message', 'Updated sale') if pk else pgettext_lazy(
                'Sale (discount) message', 'Added sale')
        messages.success(request, msg)
        return redirect('dashboard:sale-update', pk=instance.pk)
    ctx = {'sale': instance, 'form': form}
    return TemplateResponse(request, 'dashboard/discount/sale/form.html', ctx)


@staff_member_required
@permission_required('discount.edit_sale')
def sale_delete(request, pk):
    instance = get_object_or_404(Sale, pk=pk)
    if request.method == 'POST':
        instance.delete()
        messages.success(
            request,
            pgettext_lazy('Sale (discount) message', 'Deleted sale %s') % (instance.name,))
        return redirect('dashboard:sale-list')
    ctx = {'sale': instance}
    return TemplateResponse(
        request, 'dashboard/discount/sale/modal/confirm_delete.html', ctx)


@staff_member_required
@permission_required('discount.view_voucher')
def voucher_list(request):
    vouchers = (Voucher.objects.select_related('product', 'category')
                .order_by('name'))
    vouchers = get_paginator_items(
        vouchers, DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {'vouchers': vouchers}
    return TemplateResponse(
        request, 'dashboard/discount/voucher/list.html', ctx)


@staff_member_required
@permission_required('discount.edit_voucher')
def voucher_edit(request, pk=None):
    if pk is not None:
        instance = get_object_or_404(Voucher, pk=pk)
    else:
        instance = Voucher()
    voucher_form = forms.VoucherForm(request.POST or None, instance=instance)
    type_base_forms = {
        Voucher.SHIPPING_TYPE: forms.ShippingVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.SHIPPING_TYPE),
        Voucher.VALUE_TYPE: forms.ValueVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.VALUE_TYPE),
        Voucher.PRODUCT_TYPE: forms.ProductVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.PRODUCT_TYPE),
        Voucher.CATEGORY_TYPE: forms.CategoryVoucherForm(
            request.POST or None, instance=instance,
            prefix=Voucher.CATEGORY_TYPE)}
    if voucher_form.is_valid():
        voucher_type = voucher_form.cleaned_data['type']
        form_type = type_base_forms.get(voucher_type)
        if form_type is None:
            instance = voucher_form.save()
        elif form_type.is_valid():
            instance = form_type.save()

        if form_type is None or form_type.is_valid():
            msg = pgettext_lazy(
                'Voucher message', 'Updated voucher') if pk else pgettext_lazy(
                    'Voucher message', 'Added voucher')
            messages.success(request, msg)
            return redirect('dashboard:voucher-update', pk=instance.pk)
    ctx = {
        'voucher': instance, 'default_currency': settings.DEFAULT_CURRENCY,
        'form': voucher_form, 'type_base_forms': type_base_forms}
    return TemplateResponse(
        request, 'dashboard/discount/voucher/form.html', ctx)


@staff_member_required
@permission_required('discount.edit_voucher')
def voucher_delete(request, pk):
    instance = get_object_or_404(Voucher, pk=pk)
    if request.method == 'POST':
        instance.delete()
        messages.success(
            request,
            pgettext_lazy('Voucher message', 'Deleted voucher %s') % (instance,))
        return redirect('dashboard:voucher-list')
    ctx = {'voucher': instance}
    return TemplateResponse(
        request, 'dashboard/discount/voucher/modal/confirm_delete.html', ctx)

templates/dashboard/customer/detail.html
{% extends "dashboard/base.html" %}
{% load prices_i18n %}
{% load i18n %}
{% load materializecss %}
{% load status %}
{% load staticfiles %}

{% block title %}
  {{ customer }} - {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:customers" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:customers" %}">
        {% trans "Customers" context "Dashboard customers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:customers" %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li><span class="breadcrumbs--elipsed-item">{{ customer }}</span></li>
  </ul>
{% endblock %}


{% block header_extra %}
  {% if customer.pk and not customer.is_staff and request.user.is_superuser %}
    <a class="dropdown-button right" href="#" data-activates="context-menu" data-constrainwidth="false">
      <svg data-src="{% static "dashboard/images/more_vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="context-menu" class="dropdown-content">
      <li>
        <a href="#base-modal" data-href="{% url 'dashboard:customer-promote' pk=customer.pk %}"
        class="modal-trigger-custom">
          {% trans 'Promote to staff' context 'Customer promote to staff member action' %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock %}


{% block content %}
  <div class="row">
    <div class="col s12 l8">
      <div class="card">
        <div class="data-table-header{% if not customer_orders %} data-table-header--no-data{% endif %}">
          <h5 class="data-table-title">
            {% trans "Order history" context "Customer orders table title" %}
          </h5>
        </div>
        {% if customer_orders %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  <th>
                    {% trans "Number" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Placed on" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Order status" context "Customer orders table header" %}
                  </th>
                  <th class="right-align">
                    {% trans "Total" context "Customer orders table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for order in customer_orders %}
                  <tr data-action-go="{% if perms.order.view_order %}{% url 'dashboard:order-details' order_pk=order.pk %}{% endif %}">
                    <td>
                      {{ order }}
                    </td>
                    <td>
                      {{ order.created }}
                    </td>
                    <td>
                      {% render_status order.status order.get_status_display %}
                    </td>
                    <td class="right-align">
                      {% gross order.get_total html=True %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data">
            <p>
              {% trans "No orders found." context "Empty customer orders table message" %}
            </p>
          </div>
        {% endif %}
      </div>
    </div>

    <div class="col s12 l4">
       <div class="row">
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default shipping address" context "Customer default shipping address card title" %}
              </span>
              {% if customer.default_shipping_address %}
                {% with customer.default_shipping_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>{% trans "No default shipping address." context "Customer without default shipping address message" %}</div>
              {% endif %}
              <svg data-src="{% static "dashboard/images/email.svg" %}" width="14" height="14" />
              <a href="mailto:{{ customer.email }}">
                {{ customer.email }}
              </a>
            </div>
          </div>
        </div>
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default billing address" context "Customer default billing address card title" %}
              </span>
              {% if customer.default_billing_address %}
                {% with customer.default_billing_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>
                  {% trans "No default billing address." context "Customer without default billing address message" %}
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load materializecss %}
{% load utils %}

{% block title %}
  {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Customers" context "Dashboard customers list" %}
    </li>
  </ul>
{% endblock %}

{% block content %}
  {% if customers %}
    <div class="card">
      <div class="data-table-container">
        <table class="bordered highlight responsive data-table">
          <thead>
            <tr>
              <th>
                {% trans "Email" context "Customers table header" %}
              </th>
              <th class="wide">
                {% trans "Name" context "Customers table header" %}
              </th>
              <th>
                {% trans "Location" context "Customers table header" %}
              </th>
              <th class="right-align">
                {% trans "Number of orders" context "Customers table header" %}
              </th>
              <th>
                {% trans "Last order" context "Customers table header" %}
              </th>
            </tr>
          </thead>
          <tbody>
            {% for customer in customers %}
              <tr data-action-go="{% url "dashboard:customer-details" pk=customer.pk %}">
                {% with customer.default_billing_address as default_address %}
                  <td>
                    {{ customer.email }}
                  </td>
                  {% if default_address %}
                    <td>
                      {{ default_address.first_name }} {{ default_address.last_name }}
                    </td>
                    <td>
                      {{ default_address.city }}, {{ default_address.get_country_display }}
                    </td>
                  {% else %}
                    <td colspan="2"></td>
                  {% endif %}
                {% endwith %}
                <td class="right-align">
                  {{ customer.num_orders }}
                </td>
                <td class="ignore-link">
                  {% if customer.last_order %}
                    <a href="{% url 'dashboard:order-details' order_pk=customer.last_order %}">
                      {% blocktrans with last_order=customer.last_order trimmed context "Customers table last order data" %}
                        #{{ last_order }}
                      {% endblocktrans %}
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% else %}
    <div class="card-content card-content--no-data not-found">
      <p class="grey-text">
        {% trans "No customers found." context "Empty customers table message" %}
      </p>
    </div>
  {% endif %}
  {% paginate customers %}
{% endblock %}